export const NAVIGATE_TO_LOGIN = 'NAVIGATE_TO_LOGIN'
export const NAVIGATE_TO_PANEL = 'NAVIGATE_TO_PANEL'
export const AUTHORIZE = 'AUTHORIZE'
export const LOGOUT = 'LOGOUT'

export const GET_CURRENT_USER_PROFILE = 'GET_CURRENT_USER_PROFILE'
export const GET_ANOTHER_USER_PROFILE = 'GET_ANOTHER_USER_PROFILE'

export const GET_CURRENT_USER_REPOSITORIES = 'GET_CURRENT_USER_REPOSITORIES'
export const SEARCH_REPOSITORIES = 'SEARCH_REPOSITORIES'
export const TOGGLE_FORK_FILTER = 'TOGGLE_FORK_FILTER'

export const TOGGLE_DRAWER = 'TOGGLE_DRAWER'
