export const NAVIGATE_TO_LOGIN = 'NAVIGATE_TO_LOGIN'
export const NAVIGATE_TO_PANEL = 'NAVIGATE_TO_PANEL'
export const AUTHORIZE = 'AUTHORIZE'
export const LOGOUT = 'LOGOUT'

export const GET_CURRENT_USER_PROFILE = 'GET_CURRENT_USER_PROFILE'
export const GET_ANOTHER_USER_PROFILE = 'GET_ANOTHER_USER_PROFILE'
